### ISSUE TITLE
Markdown or HTML

### ISSUE THREAD

**Issue by cmprmsd** [Simpsonpt/AppSecEzine#3]
Great stuff!
Would you mind converting the files to Markdown or HTML in order to have all URLs linkified?
Markdown is the preferred solution of course!

**Comment by Simpsonpt** [comment]
Hi,

For now, I don't have any automation to do such conversion, but it is something to consider in the future. Meanwhile, all issues have an HTML version, and the link is always at the bottom. For the 435th issue, for example, you can find the link here: https://github.com/Simpsonpt/AppSecEzine/blob/3a1ded4c2c359267b1f765c99579b24e87570360/Ezines/435%20-%20AppSec%20Ezine#L130

**Comment by cmprmsd** [comment]
Great, thanks for the hint to the pathonproject HTML versions! ( Although most ezines have just `http://pathonproject.com/zb/?b333......` as truncated URL)

I noticed that it's enough for the Github Android application to rename the file to `ezine.md`. Then the links are clickable also within the application.

I created a quick automation that should rename and add each new ezine to this repo: https://github.com/cmprmsd/ezines-md
Is this ok for you? I checked the license and that should be fine. :blush:

**Comment by Simpsonpt** [comment]
The truncated URLs are not expected; I will fix that for those with that problem. Regarding your repo, feel free to do it; nothing against if it solves your problem :)

**Comment by Simpsonpt** [comment]
All issues should have a valid HTTP link at the bottom. If you are ok, I believe we can close this issue, and nevertheless, I will look to your suggestion in the future.

**Comment by cmprmsd** [comment]
> All issues should have a valid HTTP link at the bottom. If you are ok, I believe we can close this issue, and nevertheless, I will look to your suggestion in the future.

Sure! Thanks!
