### ISSUE TITLE
RSS Feed: Each news is separated instead of having a news by new edition of ezine 

### ISSUE THREAD

**Issue by Yayg** [Simpsonpt/AppSecEzine#6]
Hi and thanks a lot for your work,

This is an incredible source of informations. Just a little thing that would be nice is to have the RSS feed to publish the markdown directly for an entire Enzine instead of each line.

Example of RSS output:
![image](https://github.com/Simpsonpt/AppSecEzine/assets/4986194/4e854151-961e-4db6-aa9c-33e298a040ef)

Or maybe through a different RSS feed for the entire enzine.

Thanks a lot and if I can contribute to this in any way I would be happy to have more informations on how to do it.

Sincerely,

**Comment by Simpsonpt** [comment]
Hi,

Thank you for the support! The RSS feed distribution was a contribution by @xl-sec, and all the feed generation logic is in this [repo](https://github.com/xl-sec/AppSecEzine), so it's probably the best place to ask for such improvement or a new feed.

**Comment by xl-sec** [comment]
@Yayg sorry for the delay, now the whole ezine is published at https://xl-sec.github.io/AppSecEzine/latest_whole.rss or https://xl-sec.github.io/AppSecEzine/latest_whole.atom 

@Simpsonpt I've updated the readme in my repo, dunno if you want to just grab the markdown from there or not. The old URLs are still maintained so no real need to update...

**Comment by xl-sec** [comment]
@Yayg sorry for the delay, now the whole ezine is published at https://xl-sec.github.io/AppSecEzine/latest_whole.rss or https://xl-sec.github.io/AppSecEzine/latest_whole.atom 

@Simpsonpt I've updated the readme in my repo, dunno if you want to just grab the markdown from there or not. The old URLs are still maintained so no real need to update...

**Comment by Simpsonpt** [comment]
Thank you, @xl-sec. I believe it's fine to keep the links for now.
