### ISSUE TITLE
Webhook for the repository

### ISSUE THREAD

**Issue by kocurc** [Simpsonpt/AppSecEzine#7]
Please create a webhook for the repository.
I would like to create an n8n workflow to handle the ezines commits

**Comment by Simpsonpt** [comment]
Hi Kocurc,

I'm not entirely sure I understand your request. Generally, a webhook sends a POST request with specific information to a given URL after a particular action occurs and is configured at the repo level. I'm not familiar with creating a generic webhook for the repository.

If you need to "scrape" commit information, you might want to check out the [GitHub RSS Feed](https://github.com/Simpsonpt/AppSecEzine/commits.atom).

**Comment by kocurc** [comment]
Thank you for the scraping idea, it might be suitable for me
